@startuml sorting-test
skinparam sequenceArrowThickness 2
skinparam responseMessageBelowArrow true
hide footbox


participant exec[
    = Test Executor
    ----
    K6 Virtual User
]

participant sut [
    = System Under Test
    ----
    Demo Application
]



exec <- exec: Generate\nTest Data
exec <- exec: Sort Test Data\nFor Verification



@enduml
