name: Build Native Image
on:
  workflow_dispatch:
    inputs:
      graal-distro:
        description: 'GraalVM distribution version'
        required: true
        default: 'graalvm-community'
        type: string
      java-version:
        description: 'Java version that will be used during the build'
        required: true
        default: '21'
        type: string
      project:
        description: 'Name of the project that corresponds to directory and JAR file name'
        required: true
        default: 'demo-app'
        type: string
env:
  JAVA_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.java-version || '21' }}
  GRAAL_DISTRO: ${{ github.event_name == 'workflow_dispatch' && inputs.graal-distro || 'graalvm-community' }}
  PROJECT: ${{ github.event_name == 'workflow_dispatch' && inputs.project || 'demo-app' }}
jobs:
  build-native:
    name: Build GraalVM Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Environment Setup
        run:  | 
          echo "Java Version: $JAVA_VERSION"
          echo "Gradle Version: $GRAAL_DISTRO"
          echo "Project dir: $PROJECT"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: $JAVA_VERSION
          distribution: $GRAAL_DISTRO
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: true
          components: 'native-image'
          native-image-job-reports: 'true'
      - name: Build native-image for ${{ matrix.os }}
        run: ./gradlew nativeCompile --no-daemon
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-${{ matrix.os }}
          path: ${{ env.PROJECT }}/build/native/nativeCompile/${{ env.PROJECT }}
          if-no-files-found: error
            
