name: Build and test
on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: 'Gradle version that will be used during the build'
        required: false
        default: 'wrapper'
        type: string
      java-version:
        description: 'Java version that will be used during the build'
        required: false
        default: '21'
        type: string
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feature/*
    paths:
      - ".github/workflows/build-test-gradle-jar.yaml"
      -  "demo-app/**"
      - "!demo-app/README.md"
      - "!demo-app/gralde/**"
      - "!demo-app/graldew.bat"
env:
  JAVA_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.java-version || '21' }}
  GRADLE_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.gradle.version || 'wrapper' }}
  PROJECT_DIR: 'demo-app'
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Environment Setup
        run:  | 
          echo "Java Version: $JAVA_VERSION"
          echo "Gradle Version: $GRADLE_VERSION"
          echo "Project dir: $PROJECT_DIR"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: ${{ env.GRADLE_VERSION }}
            arguments: build -x test --no-daemon
            build-root-directory: ${{ env.PROJECT_DIR }}
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: ${{ env.GRADLE_VERSION }}
            arguments: test --no-daemon
            build-root-directory: ${{ env.PROJECT_DIR }}
