name: Update Diagrams
on:
  push:
    paths:
    - 'k6-tests/diagrams/**.plantuml'
  workflow_dispatch:
jobs:
  build-diagrams:
    name: Build *.png file from diagrams
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate diagrams
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
