name: Update Diagrams
on:
  push:
    paths:
    - 'k6-tests/diagrams/**.plantuml'
  workflow_dispatch:
jobs:
  build-diagrams:
    name: Build diagram PNG
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Download Plantuml
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2024.0/plantuml-1.2024.0.jar
      - name: Generate Diagrams
        run: java -jar plantuml-1.2024.0.jar -v -tpng -r  **/k6-tests/diagrams/*.plantuml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update UML diagrams
          commit_user_name: 'github-actions-uml[bot]'
          commit_user_email: 'latusikl@latusikl.com'
          file_pattern: '*.png'
